---
# Download Drupal using drush (--no-cache prevents checksum error).
# - name: "Drupal: Download Drupal Core."
#   command:
#     drush dl drupal-{{ drupal_core_version }} --no-cache
#     creates={{ drupal_core_path }}/index.php
#     chdir=/var/www

- name: Check if Drupal is already present.
  stat: >
    path={{ drupal_core_path }}
  register: drupal_site

- name: Check out Drupal Core to the default location.
  git: >
    repo={{ drupal_repo_url }}
    version={{ drupal_core_version }}
    update={{ drupal_keep_updated }}
    accept_hostkey=yes
    dest={{ drupal_core_path }}
  when: drupal_site.stat.exists == false

- name: Check if Drupal is already installed.
  stat: >
    path="{{ drupal_core_path }}/sites/default/settings.php"
  register: drupal_installed

- name: Install Drupal.
  command: >
    drush si {{ drupal_install_profile }} -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_password}}
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ drupal_mysql_database }}
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/sites/default/settings.php
  when: drupal_installed.stat.exists == false
  notify: restart webserver

# SEE: https://drupal.org/node/2121849#comment-8413637
- name: Set permissions properly on settings.php.
  file: >
    path={{ drupal_core_path }}/sites/default/settings.php
    mode=744

- name: Set permissions properly on files directory.
  file: >
    path={{ drupal_core_path }}/sites/default/files
    mode=777
    state=directory
    recurse=yes
